# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def install_pods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RealmSwift'
  pod "RxRealm"
end

target 'slokara' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for slokara
  install_pods

  target 'slokaraTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

  target 'slokaraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'slokara_dev' do
  use_frameworks!

  install_pods
end

target 'slokara_adhoc' do
  use_frameworks!

  install_pods
end
